name: 'Magisk Boot Patch Action'
description: "An action to download and patch your Magisk patched boot image"

inputs:
  devices:
    description: 'List of device codenames'
    required: true

  ota_link:
    description: 'OTA updater link'
    required: true

  use_magisk:
    description: 'Use Magisk to patch boot image'
    required: false
    default: true
  
  use_kitsune:
    description: 'Use Kitsune to patch boot image'
    required: false
    default: false

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download patch script
      shell: bash
      run: |
        git clone --recurse-submodules https://github.com/0xsharkboy/Magisk-Boot-Patcher script
        chmod +x script/patch_boot.sh

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y adb fastboot dos2unix unzip curl jq brotli

    - name: Extract & patch images
      shell: bash
      env:
        OTA_LINK: ${{ inputs.ota_link }}
        DEVICES: ${{ inputs.devices }}
        USE_MAGISK: ${{ inputs.use_magisk }}
        USE_KITSUNE: ${{ inputs.use_kitsune }}
      run: |
        IFS=',' read -ra device_array <<< "$DEVICES"

        for device in "${device_array[@]}"; do
          download_link=$(curl -s "${OTA_LINK}${device}.json" | jq -r ".response[0].download")
          if [ "$download_link" != "null" ]; then
            zip_name="${device}.zip"

            echo "Downloading $zip_name from ${download_link}..."
            wget -q "$download_link" -O "$zip_name"

            # Patch with Magisk
            if [ "$USE_MAGISK" = true ]; then
              echo "Using Magisk to patch $zip_name..."
              sudo ./script/patch_boot.sh $zip_name
            fi

            # Remove stock boot.img if patching with Magisk and Kitsune
            if [ "$USE_MAGISK" && "$USE_KITSUNE" ]; then
              find -type f -name 'stock-*.img' -delete
            fi

            # Patch with Kitsune
            if [ "$USE_KITSUNE" = true ]; then
              echo "Using Kitsune to patch $zip_name..."
              sudo ./script/patch_boot.sh -k $zip_name
            fi
          
            echo "Cleaning ${zip_name}..."
            rm -f "$zip_name"
          else
            echo "Download link for $device not found."
          fi
        done
