name: Patch boot images

on:
  workflow_dispatch:

jobs:
  patch_boot:
    name: Download & patch boot images
    runs-on: ubuntu-latest

    steps:
      - name: Download files
        run: |
          git clone --recurse-submodules https://github.com/0xsharkboy/Magisk-Boot-Patcher script
          echo "Downloading rom zip package..."
          wget -q https://sourceforge.net/projects/evolution-x/files/beyond2lte/14/EvolutionX-14.0-20240727-beyond2lte-v9.2-Official.zip/download -O rom.zip
          echo "Done !"

      - name: Install dependencies
        run: sudo apt install adb fastboot dos2unix unzip curl ed brotli

      - name: Extract & patch images
        run: |
          cd script
          chmod +x patch_boot.sh
          ./patch_boot.sh ../rom.zip

      - name: Upload patched images
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.TOKEN }}
          tag_name: ${{ github.run_id }}
          make_latest: "true"
          files: |
            script/out/*.img
        