name: Patch boot images

on:
  workflow_dispatch:

jobs:
  patch_boot:
    name: Download & patch boot images
    runs-on: ubuntu-latest

    env:
      DOWNLOAD_LINKS: |
        https://sourceforge.net/projects/evolution-x/files/beyond0lte/14/EvolutionX-14.0-20240726-beyond0lte-v9.2-Official.zip/download
        https://sourceforge.net/projects/evolution-x/files/beyond1lte/14/EvolutionX-14.0-20240727-beyond1lte-v9.2-Official.zip/download
        https://sourceforge.net/projects/evolution-x/files/beyond2lte/14/EvolutionX-14.0-20240727-beyond2lte-v9.2-Official.zip/download

    steps:
      - name: Download files
        run: |
          git clone --recurse-submodules https://github.com/0xsharkboy/Magisk-Boot-Patcher script
          chmod +x script/patch_boot.sh

      - name: Install dependencies
        run: sudo apt install adb fastboot dos2unix unzip curl ed brotli

      - name: Extract & patch images
        run: |
          zip_array=()

          i=0
          for link in $DOWNLOAD_LINKS; do
            zip_name="${i}.zip"
            
            echo "Downloading $zip_name from ${link}..."
            wget -q "$link" -O "$zip_name"

            zip_array+=("$zip_name")
            i=$((i + 1))
          done

          echo "Downloads completed"
          echo -e "Extracting and patching ROM packages...\n"
          sudo ./script/patch_boot.sh "${zip_array[@]}"

      - name: Upload patched images
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.TOKEN }}
          tag_name: ${{ github.run_id }}
          make_latest: "true"
          files: |
            script/out/*.img
        