name: Patch boot images

on:
  workflow_dispatch:

jobs:
  patch_boot:
    name: Download & patch boot images
    runs-on: ubuntu-latest

    env:
      DEVICES: |
        beyond0lte
        beyond2lte

      OTA_LINK: https://raw.githubusercontent.com/Evolution-XYZ/OTA/udc/builds/

    steps:
      - name: Download files
        run: |
          git clone --recurse-submodules https://github.com/0xsharkboy/Magisk-Boot-Patcher script
          chmod +x script/patch_boot.sh

      - name: Install dependencies
        run: sudo apt install adb fastboot dos2unix unzip curl ed brotli

      - name: Extract & patch images
        run: |
          zip_array=()

          i=0
          for device in $DEVICES; do
            zip_name="${i}.zip"
            download_link=$(curl "${OTA_LINK}${device}.json" | jq -r ".response[0].download")
            
            echo "Downloading $zip_name from ${download_link}..."
            wget -q "$download_link" -O "$zip_name"

            zip_array+=("$zip_name")
            i=$((i + 1))
          done

          echo "Downloads completed"
          echo -e "Extracting and patching ROM packages...\n"
          sudo ./script/patch_boot.sh "${zip_array[@]}"

      - name: Upload patched images
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.TOKEN }}
          tag_name: ${{ github.run_id }}
          make_latest: "true"
          files: |
            script/out/*.img
        